import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import {SnackbarProvider} from "@/app/context/SnackbarContext";
import {AuthProvider} from "@/app/context/AuthProviderContext";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import React from "react";
import {DialogProvider} from "@/app/context/DialogContext";

const inter = Inter({
      weight: ['300', '400', '500', '700'],
      subsets: ['latin'],
      display: 'swap',
      variable: '--font-inter',
    });

export const metadata: Metadata = {
  title: {
      default: "Read&Chill - Nhà sách thế hệ mới",
      template: '%s | Read&Chill',
  },
  description: "Generated by create next app",
  keywords: ['default', 'keywords'],
  icons: {
      icon: [
          { url: '/icon0.svg', sizes: '32x32', type: 'image/svg+xml' },
          { url: '/icon1.png', sizes: '16x16', type: 'image/png' },
      ],
      shortcut: '/favicon.ico',
      apple: '/apple-icon.png',
  }
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (

          <html lang="en">
            <body className={`${inter.className} antialiased bg-gray-100`}>
            <DialogProvider>
                <SnackbarProvider>
                    <AuthProvider>
                        <AppRouterCacheProvider>
                            <ThemeProvider theme={theme}>
                                <main className="max-w-screen-2xl mx-auto min-h-screen flex flex-col">
                                    <Header />
                                    <div className="grow">
                                        {children}
                                    </div>
                                    <Footer />
                                </main>
                            </ThemeProvider>
                        </AppRouterCacheProvider>
                    </AuthProvider>
                </SnackbarProvider>
            </DialogProvider>
            </body>
          </html>

  );
}
